<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check Student</name>
   <tag></tag>
   <elementGuidId>b5550ccf-b248-492f-bda8-2e1cde35826c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getStudentInfo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'getStudentInfo' and (text() = 'Check Student' or . = 'Check Student')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='getStudentInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18ddfd22-aaee-4f8d-a266-d37708f2e416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a777048f-3e40-4232-b21a-52132e932265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50</value>
      <webElementGuid>754234c4-55d5-4ddd-94e4-6807cc758f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getStudentInfo</value>
      <webElementGuid>4df31973-5eb8-48a0-b471-bb22d0acb5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Student</value>
      <webElementGuid>bfa0f561-2d13-4d3f-8968-eaed6938ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getStudentInfo&quot;)</value>
      <webElementGuid>9f21d319-0b18-43f5-856f-b71ba4eb111a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='getStudentInfo']</value>
      <webElementGuid>c898fe50-6fd9-40aa-b5a1-56304c38ddbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]/button</value>
      <webElementGuid>8576ad8e-bfac-4a9c-a79d-b92942ad39f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='studentId'])[1]/following::button[1]</value>
      <webElementGuid>4defcd89-42c3-43b7-8427-ce658e62866a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check you students data'])[1]/following::button[1]</value>
      <webElementGuid>19a8aa99-fcb9-49e3-b103-3b56d8dca242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Partial Students id'])[1]/preceding::button[1]</value>
      <webElementGuid>b7578b23-5320-4783-a1a0-a8121f6b0724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Student']/parent::*</value>
      <webElementGuid>448983fe-429b-4c89-b194-06d71a13c6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c5eadc15-41eb-4881-bd7a-178396cf130d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'getStudentInfo' and (text() = 'Check Student' or . = 'Check Student')]</value>
      <webElementGuid>58af69cc-7f1d-4700-a6e0-36eb99c050d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
