<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check Partial Students id</name>
   <tag></tag>
   <elementGuidId>a1839105-efdf-4576-b483-b466ed76d46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getStudentsInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='getStudentsInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b3407b1c-b590-44a6-a158-6f0787502fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5f46d6d-b5bf-4733-b766-46bf3df555db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-3 inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50</value>
      <webElementGuid>82cfd1f4-da8c-492b-adc8-8eddf95d77ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getStudentsInfo</value>
      <webElementGuid>0bb54190-dd94-4fdd-aa88-939ab034fc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Partial Students id</value>
      <webElementGuid>40f6b83f-863c-4c9e-a62a-386daef7c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getStudentsInfo&quot;)</value>
      <webElementGuid>681cf996-b9f6-4c12-83ee-3f14daf2ce06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='getStudentsInfo']</value>
      <webElementGuid>9dd013c7-6d7b-4add-a9a3-0fcd6c6d9873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>05a8a3a0-c282-4ec3-a1f2-390759be00e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Student'])[1]/following::button[1]</value>
      <webElementGuid>64490463-4b9f-4ab1-b0fc-12562dbf3468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='studentId'])[1]/following::button[2]</value>
      <webElementGuid>e5ce3711-31a4-4158-b887-dc14af07a08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Partial Students id']/parent::*</value>
      <webElementGuid>68cb01ba-a179-4087-b28d-88f8a2e259f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dbb3ac02-46d5-45a0-b97e-264b22f12485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'getStudentsInfo' and (text() = 'Check Partial Students id' or . = 'Check Partial Students id')]</value>
      <webElementGuid>b95aa9a1-59c9-4479-9d3e-8e2d1231b75b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
