<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_total_gpa</name>
   <tag></tag>
   <elementGuidId>7deaec5a-9809-49f0-968f-67faaa741782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='totalGPA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#totalGPA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76368a90-7e17-40f0-948c-3d3b2c2a84aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalGPA</value>
      <webElementGuid>5fd42362-836d-49ac-9fc6-ff54709043e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3.50</value>
      <webElementGuid>4149b444-2723-49c9-9771-3277de1c31e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalGPA&quot;)</value>
      <webElementGuid>69326979-8e2c-4be0-a935-908c9b37c330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='totalGPA']</value>
      <webElementGuid>34e6b0a0-6c84-497f-8b8c-2c460194982a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/table/tfoot/tr/td[3]/div</value>
      <webElementGuid>ae9f25e3-39b7-4b7f-8c5a-4ec20ee1b06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total GPA'])[1]/following::div[1]</value>
      <webElementGuid>cd0f34b5-e99d-42f3-a8fa-e454febb2146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chinner'])[1]/following::div[1]</value>
      <webElementGuid>38c90c01-88c0-4553-bdb4-e52242b218ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>93ee4f44-2e71-4650-b12b-07e09a68d62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'totalGPA' and (text() = '3.50' or . = '3.50')]</value>
      <webElementGuid>18cbafc1-ade2-4901-aa3c-457159fb7a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
